export { default as Home } from "./Home/Home";
export { default as Services } from "./Services/Services";
export { default as InAppPlans } from "./InAppPlans/InAppPlans";
export { default as Cities } from "./Cities/Cities";
export { default as Contract } from "./Contract/Contract";
export { default as Login } from "./Login/Login";
export { default as Signup } from "./Signup/Signup";
export { default as AddPackage } from "./AddPackage/AddPackage";
export { default as CheckOut } from "./CheckOut/CheckOut";
export { default as AddRestaurant } from "./AddRestaurant/AddRestaurant";
export { default as AddService } from "./AddService/AddService";
export { default as Bookings } from "./Bookings/Bookings";
export { default as HelpAndSupport } from "./HelpAndSupport/HelpAndSupport"
export { default as GenericInfoAboutService } from "./GenericInfoAboutService/GenericInfoAboutService"
export { default as Listing } from "./Listing/Listing";
export { default as BlogPage } from "./BlogPage/BlogPage";
export { default as AddBlog } from "./AddBlog/AddBlog";
export { default as Blogs } from "./Blogs/Blogs";
export { default as SpotListing } from "./SpotListing/SpotListing";
export { default as ForgetPassword } from "./ForgetPassword/ForgetPassword";
export { default as ResetPassword } from "./ResetPassword/ResetPassword";
export { default as TourGuideListing } from "./TourGuideListing/TourGuideListing";
export { default as AddTourGuide } from "./AddTourGuide/AddTourGuide";
export { default as AddHotel } from "./AddHotel/AddHotel"
export { default as AddHotelRoom } from "./AddHotelRoom/AddHotelRoom"
export { default as RestaurantListing } from "./RestaurantListing/RestaurantListing";           
export {default as AccountVerification } from "./AccountVerification/AccountVerification"