export const questions =
   [
      { "question": "What is tourPk?", "answer": "tourPk is an online marketplace that allows tourists to book tour packages, make online payments, and create and share blog posts about their experiences in Pakistan." },
      { "question": "How do I create an account on tourPk?", "answer": "You can create an account on tourPk by clicking the 'Sign up' button on the top right corner of the website and following the registration process." },
      { "question": "How do I book a tour package on tourPk?", "answer": "You can book a tour package on tourPk by selecting the desired package, choosing the number of people, selecting the date and time, and making the payment online through our secure payment gateway." },
      { "question": "How do I make an online payment on tourPk?", "answer": "You can make an online payment on tourPk through our secure payment gateway. Simply select your preferred payment method and follow the instructions." },
      { "question": "Can I cancel a tour package booking on tourPk?", "answer": "Yes, you can cancel a tour package booking on tourPk. However, cancellation policies may vary depending on the service provider. Please refer to the cancellation policy on the package details page for more information." },
      { "question": "What should I do if I encounter a problem with a service provider on tourPk?", "answer": "If you encounter a problem with a service provider on tourPk, please contact our customer support team through the 'Help & Support' section on the website, and we will do our best to resolve the issue." },
      { "question": "How do I share my experience on tourPk?", "answer": "You can share your experience on tourPk by creating and publishing a blog post on the website. Simply log in to your account, click on the 'Blog' tab, and follow the instructions to create your post." },
      { "question": "What should I do if I forget my tourPk password?", "answer": "If you forget your tourPk password, simply click on the 'Forgot password' link on the login page and follow the instructions to reset your password." }, { "question": "How do I contact tourPk customer support?", "answer": "You can contact tourPk customer support through the 'Help & Support' section on the website, where you can submit a support ticket with your query. Our customer support team will respond to you as soon as possible." }
   ]
