export const amenities = [
    { name: 'Lobby area', label: 'Lobby area' },
    { name: 'Reception desk', label: 'Reception desk' },
    { name: 'Concierge services', label: 'Concierge services' },
    { name: 'Restaurant(s)', label: 'Restaurant(s)' },
    { name: 'Bar(s) or lounge(s)', label: 'Bar(s) or lounge(s)' },
    { name: 'Room service', label: 'Room service' },
    { name: 'Fitness center or gym', label: 'Fitness center or gym' },
    { name: 'Swimming pool (indoor or outdoor)', label: 'Swimming pool (indoor or outdoor)' },
    { name: 'Spa or wellness center', label: 'Spa or wellness center' },
    { name: 'Business center', label: 'Business center' },
    { name: 'Conference and meeting rooms', label: 'Conference and meeting rooms' },
    { name: 'Free Wi-Fi or internet access', label: 'Free Wi-Fi or internet access' },
    { name: '24-hour front desk', label: '24-hour front desk' },
    { name: 'Express check-in and check-out', label: 'Express check-in and check-out' },
    { name: 'Elevators or lifts', label: 'Elevators or lifts' },
    { name: 'Laundry services', label: 'Laundry services' },
    { name: 'Currency exchange', label: 'Currency exchange' },
    { name: 'On-site parking', label: 'On-site parking' },
    { name: 'Shuttle service', label: 'Shuttle service' },
    { name: 'Airport transportation', label: 'Airport transportation' },
];
